import{a as w,S as L,i}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const k="49372169-96077d899f4beec9c9139b15f",C="https://pixabay.com/api/";document.querySelector("input");async function m(o,t){const s=new URLSearchParams({key:k,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});return(await w.get(`${C}?${s}`)).data}const M=document.querySelector(".gallery"),P=new L(".gallery a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionDelay:250});function d(o){const t=o.hits.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:l,comments:S,downloads:q})=>`<li class="gallery-item">
    <a class="gallery-link" href="${s}">
    <img
    class="gallery-image"
    src="${a}"
    alt= "${e.split(", ").slice(0,3).join(", ")}"
    width="360px"
    height="200px"
    />
    </a>
    <ul class="image-titles">
    <li>Likes<br>${r}</br></li>
    <li>Views<br>${l}</br></li>
    <li>Comments<br>${S}</br></li>
    <li>Downloads<br>${q}</br></li>
    </ul>
    </li>`).join("");M.insertAdjacentHTML("beforeend",t),P.refresh()}const v=document.querySelector("form"),O=document.querySelector("input"),y=document.querySelector(".button-more"),p=document.querySelector(".loader"),g=document.querySelector(".more");let n=1,u="";const h=15;let f=0;const b=()=>y.style.display="block",c=()=>y.style.display="none";v.addEventListener("submit",R);async function R(o){if(o.preventDefault(),document.querySelector(".gallery").innerHTML="",u=O.value.trim(),!u){i.error({message:"Please enter a search query before submitting!",position:"topRight"});return}p.style.display="block",c();try{const t=await m(u,n);if(f=Math.ceil(t.totalHits/h),t.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",closeOnClick:!0,color:"#fafafb",messageColor:"#fafafb",backgroundColor:"#ef4040"}),c();return}if(d(t),n+=1,n>f)return c(),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."});b()}catch{i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",closeOnClick:!0,color:"#fafafb",messageColor:"#fafafb",backgroundColor:"#ef4040"})}finally{p.style.display="none"}}y.addEventListener("click",$);async function $(){c(),g.style.display="block";try{let t=function(){const s=document.querySelector(".gallery-item");if(s){const e=s.getBoundingClientRect().height*2;window.scrollBy({top:e,behavior:"smooth"})}};const o=await m(u,n);if(f=Math.ceil(o.totalHits/h),d(o),n+=1,t(),n>f)return c(),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."});b()}catch{i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",closeOnClick:!0,color:"#fafafb",messageColor:"#fafafb",backgroundColor:"#ef4040"})}finally{g.style.display="none"}}
//# sourceMappingURL=index.js.map
