import{a as q,S as w,i}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const L="49372169-96077d899f4beec9c9139b15f",k="https://pixabay.com/api/";document.querySelector("input");async function g(o,t){const s=new URLSearchParams({key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});return(await q.get(`${k}?${s}`)).data}const C=document.querySelector(".gallery"),M=new w(".gallery a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionDelay:250});function m(o){const t=o.hits.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:n,comments:b,downloads:S})=>`<li class="gallery-item">
    <a class="gallery-link" href="${s}">
    <img
    class="gallery-image"
    src="${a}"
    alt= "${e.split(", ").slice(0,3).join(", ")}"
    width="360px"
    height="200px"
    />
    </a>
    <ul class="image-titles">
    <li>Likes<br>${r}</br></li>
    <li>Views<br>${n}</br></li>
    <li>Comments<br>${b}</br></li>
    <li>Downloads<br>${S}</br></li>
    </ul>
    </li>`).join("");C.insertAdjacentHTML("beforeend",t),M.refresh()}const P=document.querySelector("form"),v=document.querySelector("input"),f=document.querySelector(".button-more"),y=document.querySelector(".loader"),p=document.querySelector(".more");let c="";const d=15;let u=0;const h=()=>f.style.display="block",l=()=>f.style.display="none";P.addEventListener("submit",O);page=1;async function O(o){if(o.preventDefault(),document.querySelector(".gallery").innerHTML="",c=v.value.trim(),!c){i.error({message:"Please enter a search query before submitting!",position:"topRight"});return}y.style.display="block",l();try{const t=await g(c,page);if(u=Math.ceil(t.totalHits/d),t.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",closeOnClick:!0,color:"#fafafb",messageColor:"#fafafb",backgroundColor:"#ef4040"}),l();return}if(m(t),page+=1,page>u)return l(),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."});h()}catch{i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",closeOnClick:!0,color:"#fafafb",messageColor:"#fafafb",backgroundColor:"#ef4040"})}finally{y.style.display="none"}}f.addEventListener("click",R);async function R(){l(),p.style.display="block";try{let t=function(){const s=document.querySelector(".gallery-item");if(s){const e=s.getBoundingClientRect().height*2;window.scrollBy({top:e,behavior:"smooth"})}};const o=await g(c,page);if(u=Math.ceil(o.totalHits/d),m(o),page+=1,t(),page>u)return l(),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."});h()}catch{i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",closeOnClick:!0,color:"#fafafb",messageColor:"#fafafb",backgroundColor:"#ef4040"})}finally{p.style.display="none"}}
//# sourceMappingURL=index.js.map
